config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'rides#index'
  get '/rides' => 'rides#index'
  post '/rides' => 'rides#create'

  namespace :api do
    namespace :v1 do
      get '/rides' => 'rides#index'
      post '/rides' => 'rides#create'
      get '/rides/:id' => 'rides#show'
      put '/rides/:id' => 'rides#update'
    end
  end

  get '/signup' => 'users#new'
  get '/users' => 'users#index'
  post '/users' => 'users#create'
  get '/users/:id' => 'users#show'

  namespace :api do
    namespace :v1 do
      get '/users' => 'users#index'
      get '/users/:id' => 'users#show'
    end
  end

  post '/friendships' => 'friendships#create'
  delete 'friendships/:id' => 'friendships#destroy'

  namespace :api do
    namespace :v1 do
      get '/friendships' => 'friendships#index'
      get '/friendships/:id' => 'friendships#show'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/comments' => 'comments#index'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/likes' => 'likes#index'
      get '/likes/:id' => 'likes#show'
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ride
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => "User"

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :ride
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :rides
  has_many :comments
  has_many :likes

  def friend?(input_id)
    friendships = Friendship.all.where(user_id: self.id)
    friendships.each do |friendship|
      if friendship.friend_id == input_id
        return true
      end
    end
    false
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @comments = Comment.all
    render 'index.json.jbuilder'
  end
end

app/controllers/api/v1/likes_controller.rb
class Api::V1::LikesController < ApplicationController
  def index
    @likes = Like.all
    render 'index.json.jbuilder'
  end

  def show
    @likes = Like.where(ride_id: params[:id])
    render 'show.json.jbuilder'
  end
end

app/controllers/api/v1/rides_controller.rb
class Api::V1::RidesController < ApplicationController
  def index
    @user = User.all
    @rides = Ride.all.sort_by{|ride| ride.created_at}.reverse
    render 'index.json.jbuilder'
  end

  def create
    @ride = Ride.new(
      starting_location: params[:starting_location],
      ending_location: params[:ending_location],
      miles: params[:miles],
      in_progress: params[:in_progress],
      finished: params[:finished],
      user_id: params[:user_id],
      top_five: params[:top_five]
    )
    if @ride.save
      render json: @ride 
    else
      render json: {errors: "Didn't save"},
        status: 420
    end
  end

  def show
    @ride = Ride.find_by(id: params[:id])
    @likes = Like.where(ride_id: params[:id])
    render 'show.json.jbuilder'
  end

  def update
    ride = Ride.find_by(id: params[:id])
    user = User.find_by(id: ride.user_id)
    if (params[:miles])
      user.miles == nil ? new_miles = ride.miles : new_miles = ride.miles + user.miles
      @ride_updated = ride.update(
        in_progress: false,
        finished: true
      )
      @user_update = user.update(
        miles: new_miles
      )
      @ride_updated && @user_update ? render json: {ride: "completed"} : render json: {error: "error"}, status: 422
    elsif (params[:comment])
      comment = Comment.create(
        user_id: current_user.id,
        ride_id: ride.id,
        comment_text: params[:comment]
      )
    elsif (params[:liked])
      p "***********************"
      p "LIKED conditional is up"
      p "***********************"
      like = Like.find_by(ride_id: ride.id, user_id: user.id)
      if !like
        Like.create(
          user_id: current_user.id,
          ride_id: ride.id
        )
      else
        like.destroy
      end
      p like
    else
      p "comment conditional did not hit and neither did params[:miles]"
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all
    render 'index.json.jbuilder'
  end

  def show
    @user = User.find_by(id: params[:id])
    render 'show.json.jbuilder'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to '/login' unless current_user
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Successfully created friendship"
      redirect_to "/users"
    else
      flash[:error] = "Unable to add friend"
      redirect_to "/users"
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new.html.erb'
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = 'Successfully logged in!'
      redirect_to "/users/#{user.id}"
    else
      flash[:warning] = 'Invalid email or password'
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Successfully logged out!'
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
    render 'index.html.erb'
  end

  def new
    render 'new.html.erb'
  end

  def create
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if user.save
      session[:user_id] = user.id 
      flash[:success] = 'Successfully created account!'
      redirect_to "/users/#{user.id}"
    else
      flash[:warning] = 'Invalid email or password!'
      redirect_to '/signup'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/friendships_helper.rb
module Api::V1::FriendshipsHelper
end

app/helpers/api/v1/likes_helper.rb
module Api::V1::LikesHelper
end

app/helpers/api/v1/rides_helper.rb
module Api::V1::RidesHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rides/index.html.erb
<div id="app">
  <div id="weather-box"></div>
  <% if current_user %>
  <div id="user-id"><%= current_user.id %></div>
  <% end %>
  <div id="milesBox">
    <span id="rideMiles"></span> mi
  </div>

  <input id="origin-input" v-model="newOrigin" class="controls" type="text"
      placeholder="Enter an origin location">

  <input id="destination-input" v-model="newDestination" class="controls" type="text"
      placeholder="Enter a destination location">

  <div id="map">
  </div>
  <div id="save-ride">
  <% if current_user %>
    <a class="btn btn-block ride-button" v-on:click="createRide()" href="/users/<%= current_user.id %>">Start My Ride</a>
  </div>
  <% else %>
  <a class="btn btn-block ride-button" href="/login">Log In To Track Miles</a>
  <% end %>
  </div>

  <% if !current_user %>
    <div id="front-page">
      Bike Parkway
      <i class="fa fa-bicycle" aria-hidden="true"></i>
  </div>

  <div id="front-page-buttons">
    <a href="/login">Login</a>
    <i class="fa fa-road" aria-hidden="true"></i>
    <a href="/signup">Signup</a>
  </div>
  <% else %>
    <div id="front-page">
      Bike Parkway
      <i class="fa fa-bicycle" aria-hidden="true"></i>
    </div>

    <div id="front-page-buttons">
      <a href="/users/<%= current_user.id %>">Home</a>
    </div>
  <% end %>

</div>

<footer class="footer">
  <% if current_user %>
    <a href="/users/<%= current_user.id %>">Home</a>
    <span class="chain-link">-</span>
    <a href="/logout">Log Out</a>
  <% else %>
    <a href="/login">Log In</a>
    <span class="chain-link">-</span>
    <a href="/signup">Sign Up</a>
  <% end %>
</footer>

<script src="map.js">
</script>
<script src="rides.js">
</script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&libraries=places&callback=initMap">
</script>

app/views/rides/new.html.erb
Rides New Page

<%= form_tag '/rides', method: :post do %>
  <p><input type="text" name="starting_location"></p>
  <p><input type="text" name="ending_location"></p>
  <p><input type="submit" name="Get Directions"></p>
<% end %>

app/views/rides/show.html.erb
<h1>Rides Show Page</h1>

<input id="origin-input" class="controls" type="text"
    placeholder="Enter an origin location">

<input id="destination-input" class="controls" type="text"
    placeholder="Enter a destination location">

<% if current_user %>
  <p>User email: <%= @ride.user.email %></p>
<% end %>

<div id="miles_box">Miles:<span id="miles_count"></span></div>


<div id="save_ride">
  <button>Start My Ride</button>
</div>
<hr>

<div id="map"></div>
<script src="rides.js">
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&libraries=places&callback=initMap">
</script>

app/views/users/index.html.erb
<h1>User List</h1>

<div id="users">
  <% @users.each do |user| %>
    <div class="user">
      <% if user.id != current_user.id  && !current_user.friend?(user.id) %>
        <p> <%= user.first_name %> <%= user.last_name %></p>
        <% if current_user %>
          <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
        <% end %>
        <hr>
      <% end %>
    </div>
  <% end %>
</div>

<footer class="footer">
  <% if current_user %>
    <a href="/users/<%= current_user.id %>">Home</a>
    <a href="/logout">Log Out</a>
  <% else %>
    <a href="/login">Log In</a>
    <a href="/signup">Sign Up</a>
  <% end %>
</footer>

app/views/users/new.html.erb
<div class="login-form">
  <%= form_tag '/users', method: :post do %>
      <div class="form-group">
        <label for="firstName">First Name: </label><input type="text" name="first_name" class="form-control">    
      </div>
      <div class="form-group">
        <label for="lastName">Last Name: </label><input type="text" name="last_name" class="form-control">
      </div>
      <div class="form-group">
        <label for="email">Email:</label><input type="email" name="email" class="form-control">
      </div>
      <div class="form-group">
        <label for="password">Password: </label><input type="password" name="password" class="form-control">
      </div>
      <div class="form-group">
        <label for="confirmPassword">Confirm Password: </label><input type="password" name="password_confirmation" class="form-control">
      </div>
      <button type="submit" class="btn btn-block" name="submit">Submit</button>
  <% end %>
</div>

app/views/users/show.html.erb
<div id="app">
  <div id="userId"><%= @user.id %></div>
  <div v-for="ride in inProgressRides">
    <div class="in-progress-bar">
      <span>{{ ride.starting_location }}</span>
      <span>{{ ride.ending_location }}</span>
      <span>{{ ride.miles }} Miles</span>
      <button class="btn in-progress-button" v-on:click="finishRide(ride)"><i class="fa fa-flag-checkered fa-fw" aria-hidden="true"></i>
    </div>
  </div>
  <div id="title-box">    
    <p class="feature-box-header title-box-writing"><%= @user.first_name %>'s Miles</p>
  </div>
  <div id="userMilesBox">
    {{ miles }} MI
  </div>
  <div class="sort-button-row">
    <span v-on:click="makeMilesBoxLifetime() + makeRankingsLifetime()" id="lifetime-button" class="selected-miles"> Lifetime</span>
    <span v-on:click="makeMilesBoxWeekly() + makeRankingsWeekly()" id="weekly-button"> Weekly</span>
    <span v-on:click="makeMilesBoxDaily() + makeRankingsDaily()" id="today-button"> Today</span>
  </div>
<!--   <a href="/rides" class="btn btn-block bike-button"><i class="fa fa-bicycle fa-2x"></i></a> -->
  
<!--   <div id="front-page">
      Bike Parkway
      <i class="fa fa-bicycle" aria-hidden="true"></i>
  </div> -->

  <div id="front-page-buttons">
    <a href="/rides">Ride</a>
    <i class="fa fa-road" aria-hidden="true"></i>
  </div>

  <div id="friend-box">
    <p class="feature-box-header">Rankings</p>
      <div v-for="(friend, index) in sortedFriends">
        <div id="rankings">
          <p v-if="firstPlace(index)">
            {{ friend.firstName }} {{ friend.miles }}
            <i class="fa fa-trophy" aria-hidden="true"></i>
          </p>
          <p v-else>
            {{ friend.firstName }} {{ friend.miles }}
          </p>
        </div>
      </div>
  </div>    

  <div id="activity-box">
    <div class="feature-box-header">
      Road Activity
    </div>
      
      <div class="activityRides" v-for="ride in sortedRides">
        <div>
          <i class="fa fa-road" aria-hidden="true"></i>
          {{ ride.firstName }} biked {{ ride.miles }} miles.
          {{ ride.date }}
        </div>
        <!-- <div>
        <span>{{ ride.likes.length }}</span> like this
        </div>

        <div v-bind:id="'like' + ride.rideId">
            <i class="fa fa-thumbs-up" aria-hidden="true" v-on:click="likeRide(ride.rideId)"></i>
            Like
        </div> -->
        <input class="commentBox" type="text" placeholder="Write comment" v-bind:id="ride.rideId" v-on:keyup.enter="addComment(ride.rideId)"></input>
        <div v-bind:id="'comment' + ride.rideId">
          <div v-for="comment in ride.rideComments">
            <div class="commentClass">
              <a v-bind:href="'/users/' + comment.comment_user_id"> {{ comment.comment_first_name }} </a> {{ comment.comment_text }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<footer class="footer">
  <% if current_user %>
    <a href="/users">Make Friends</a>
    <span class="chain-link">-</span>
    <a href="/rides">New Ride</a>
    <span class="chain-link">-</span>
    <a href="/logout">Log Out</a>
  <% else %>
    <a href="/signup">Sign Up</a>
  <% end %>
</footer>